services:
  sunracingdb:
    image: mysql:8.0
    container_name: sunracing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./sunracing-database/db:/var/lib/mysql
    networks:
      - sunracingnetwork

  sunracing-backend:
    build: 
      context: .
      tags:
        - "sun-racing-spirit-backend:latest"
    container_name: sunracing-backend
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
      SUPERADMIN_EMAIL: ${SUPERADMIN_EMAIL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      API_CORS_ALLOWED_ORIGINS: ${API_CORS_ALLOWED_ORIGINS}
      FILE_UPLOAD_LOCATION: upload
      APP_UPLOAD_DIR_PRODUCT_IMAGES: /app/upload-dir/product-images
      APP_UPLOAD_DIR_REVIEW_IMAGES: /app/upload-dir/review-images
    ports:
      - "8080:8080"
    volumes:
      - ./upload-dir:/app/upload-dir
    depends_on:
      - sunracingdb
    networks:
      - sunracingnetwork

networks:
  sunracingnetwork:
    driver: bridge
